### ISSUE TITLE
variadic command could be removed - use proc args

### ISSUE THREAD

**Issue by endofexclusive** [howerj/pickle#12]
The Tcl way of giving variable number of arguments to a procedure is to use `proc` with the special `args` argument. For example:
```
% proc ex {args} {puts [llength $args]}
% ex
0
% ex one
1
% ex one two three
3
```
Tcl documentation on `proc`: https://www.tcl.tk/man/tcl/TclCmd/proc.htm

Implementing this in pickle would improve compatibility with Tcl. It would probably also remove the need for the custom pickle command `variadic`.

**Comment by howerj** [comment]
Hmmm, I will have to think about how I would implement this efficiently, I'll leave this open but it may not get solved for a while. 

I think the best way may be to add a flag to the 'pickle_command' structure that says the last argument was 'args', which would get set when the argument was defined. Otherwise the last would need to be checked at run time to see if was 'args', which could slow things down.

**Comment by howerj** [comment]
I've implemented this now, and added a few tests for it.

**Comment by endofexclusive** [comment]
Great!

One thing is not fully clear to me in`picolCommandCallProc()`: Is the `picolStrdup(alist)` needed?
There seems to be no writes to `alist` via `p`. But maybe there is some place in `picolCommandCallProc()` where `alist` could be deallocated while still being parsed?

The `shell` tests you added for args are spot on.

**Comment by howerj** [comment]
There is one write where a NUL terminating character is written to *p*. I think it was like this in the original 'picol.c' file as well. It's needed to we can call 'pickle\_set\_var\_string' on the substring of 'alist' that is needed.

Cheers for the feedback!
